name: GitHub CI Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello Gauthier, GitHub CI is working!"
